export interface CountryInfo {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  flag: string;
  currency: string;
  currencySymbol: string;
  currencyName: string;
  phoneCode: string;
  ratePerCode: number; // base tier rate in local currency
}

export const COUNTRIES: CountryInfo[] = [
  // West & Sub-Saharan Africa (Primary Market)
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    currency: "NGN",
    currencySymbol: "₦",
    currencyName: "Nigerian Naira",
    phoneCode: "+234",
    ratePerCode: 12,
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    currency: "GHS",
    currencySymbol: "₵",
    currencyName: "Ghanaian Cedi",
    phoneCode: "+233",
    ratePerCode: 0.12,
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    currency: "KES",
    currencySymbol: "KSh",
    currencyName: "Kenyan Shilling",
    phoneCode: "+254",
    ratePerCode: 1.05,
  },
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    currency: "ZAR",
    currencySymbol: "R",
    currencyName: "South African Rand",
    phoneCode: "+27",
    ratePerCode: 0.15,
  },
  {
    code: "EG",
    name: "Egypt",
    flag: "🇪🇬",
    currency: "EGP",
    currencySymbol: "E£",
    currencyName: "Egyptian Pound",
    phoneCode: "+20",
    ratePerCode: 0.38,
  },
  {
    code: "RW",
    name: "Rwanda",
    flag: "🇷🇼",
    currency: "RWF",
    currencySymbol: "FRw",
    currencyName: "Rwandan Franc",
    phoneCode: "+250",
    ratePerCode: 10.5,
  },
  {
    code: "UG",
    name: "Uganda",
    flag: "🇺🇬",
    currency: "UGX",
    currencySymbol: "USh",
    currencyName: "Ugandan Shilling",
    phoneCode: "+256",
    ratePerCode: 30.0,
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    currency: "TZS",
    currencySymbol: "TSh",
    currencyName: "Tanzanian Shilling",
    phoneCode: "+255",
    ratePerCode: 20.8,
  },
  {
    code: "ET",
    name: "Ethiopia",
    flag: "🇪🇹",
    currency: "ETB",
    currencySymbol: "Br",
    currencyName: "Ethiopian Birr",
    phoneCode: "+251",
    ratePerCode: 0.95,
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    currency: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
    phoneCode: "+225",
    ratePerCode: 4.8,
  },
  {
    code: "SN",
    name: "Senegal",
    flag: "🇸🇳",
    currency: "XOF",
    currencySymbol: "CFA",
    currencyName: "West African CFA Franc",
    phoneCode: "+221",
    ratePerCode: 4.8,
  },
  {
    code: "CM",
    name: "Cameroon",
    flag: "🇨🇲",
    currency: "XAF",
    currencySymbol: "FCFA",
    currencyName: "Central African CFA Franc",
    phoneCode: "+237",
    ratePerCode: 4.8,
  },
  {
    code: "MA",
    name: "Morocco",
    flag: "🇲🇦",
    currency: "MAD",
    currencySymbol: "DH",
    currencyName: "Moroccan Dirham",
    phoneCode: "+212",
    ratePerCode: 0.08,
  },

  // North America
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    currencyName: "US Dollar",
    phoneCode: "+1",
    ratePerCode: 0.008,
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "CA$",
    currencyName: "Canadian Dollar",
    phoneCode: "+1",
    ratePerCode: 0.011,
  },
  {
    code: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    currency: "MXN",
    currencySymbol: "MX$",
    currencyName: "Mexican Peso",
    phoneCode: "+52",
    ratePerCode: 0.16,
  },

  // Europe & UK
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    currencyName: "British Pound",
    phoneCode: "+44",
    ratePerCode: 0.006,
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+49",
    ratePerCode: 0.007,
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+33",
    ratePerCode: 0.007,
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    currency: "CHF",
    currencySymbol: "CHF",
    currencyName: "Swiss Franc",
    phoneCode: "+41",
    ratePerCode: 0.007,
  },
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+31",
    ratePerCode: 0.007,
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+39",
    ratePerCode: 0.007,
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+34",
    ratePerCode: 0.007,
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+32",
    ratePerCode: 0.007,
  },
  {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    currency: "SEK",
    currencySymbol: "kr",
    currencyName: "Swedish Krona",
    phoneCode: "+46",
    ratePerCode: 0.08,
  },
  {
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    currency: "NOK",
    currencySymbol: "kr",
    currencyName: "Norwegian Krone",
    phoneCode: "+47",
    ratePerCode: 0.08,
  },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    currency: "DKK",
    currencySymbol: "kr",
    currencyName: "Danish Krone",
    phoneCode: "+45",
    ratePerCode: 0.05,
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+353",
    ratePerCode: 0.007,
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+351",
    ratePerCode: 0.007,
  },
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+43",
    ratePerCode: 0.007,
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    currency: "PLN",
    currencySymbol: "zł",
    currencyName: "Polish Złoty",
    phoneCode: "+48",
    ratePerCode: 0.03,
  },

  // Middle East
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "د.إ",
    currencyName: "UAE Dirham",
    phoneCode: "+971",
    ratePerCode: 0.03,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    currency: "SAR",
    currencySymbol: "﷼",
    currencyName: "Saudi Riyal",
    phoneCode: "+966",
    ratePerCode: 0.03,
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    currency: "QAR",
    currencySymbol: "QR",
    currencyName: "Qatari Riyal",
    phoneCode: "+974",
    ratePerCode: 0.03,
  },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    currency: "KWD",
    currencySymbol: "KD",
    currencyName: "Kuwaiti Dinar",
    phoneCode: "+965",
    ratePerCode: 0.0025,
  },

  // Asia Pacific
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    currencyName: "Indian Rupee",
    phoneCode: "+91",
    ratePerCode: 0.65,
  },
  {
    code: "CN",
    name: "China",
    flag: "🇨🇳",
    currency: "CNY",
    currencySymbol: "¥",
    currencyName: "Chinese Yuan",
    phoneCode: "+86",
    ratePerCode: 0.058,
  },
  {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    currency: "JPY",
    currencySymbol: "¥",
    currencyName: "Japanese Yen",
    phoneCode: "+81",
    ratePerCode: 1.2,
  },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    currency: "SGD",
    currencySymbol: "S$",
    currencyName: "Singapore Dollar",
    phoneCode: "+65",
    ratePerCode: 0.011,
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: "A$",
    currencyName: "Australian Dollar",
    phoneCode: "+61",
    ratePerCode: 0.012,
  },
  {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    currency: "NZD",
    currencySymbol: "NZ$",
    currencyName: "New Zealand Dollar",
    phoneCode: "+64",
    ratePerCode: 0.013,
  },
  {
    code: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    currency: "KRW",
    currencySymbol: "₩",
    currencyName: "South Korean Won",
    phoneCode: "+82",
    ratePerCode: 10.8,
  },
  {
    code: "MY",
    name: "Malaysia",
    flag: "🇲🇾",
    currency: "MYR",
    currencySymbol: "RM",
    currencyName: "Malaysian Ringgit",
    phoneCode: "+60",
    ratePerCode: 0.035,
  },
  {
    code: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    currency: "IDR",
    currencySymbol: "Rp",
    currencyName: "Indonesian Rupiah",
    phoneCode: "+62",
    ratePerCode: 125.0,
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    currency: "PHP",
    currencySymbol: "₱",
    currencyName: "Philippine Peso",
    phoneCode: "+63",
    ratePerCode: 0.45,
  },
  {
    code: "TH",
    name: "Thailand",
    flag: "🇹🇭",
    currency: "THB",
    currencySymbol: "฿",
    currencyName: "Thai Baht",
    phoneCode: "+66",
    ratePerCode: 0.28,
  },
  {
    code: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    currency: "VND",
    currencySymbol: "₫",
    currencyName: "Vietnamese Dong",
    phoneCode: "+84",
    ratePerCode: 198.0,
  },
  {
    code: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
    currency: "PKR",
    currencySymbol: "₨",
    currencyName: "Pakistani Rupee",
    phoneCode: "+92",
    ratePerCode: 2.2,
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    currency: "BDT",
    currencySymbol: "৳",
    currencyName: "Bangladeshi Taka",
    phoneCode: "+880",
    ratePerCode: 0.95,
  },

  // Latin America
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    currency: "BRL",
    currencySymbol: "R$",
    currencyName: "Brazilian Real",
    phoneCode: "+55",
    ratePerCode: 0.045,
  },
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    currency: "ARS",
    currencySymbol: "$",
    currencyName: "Argentine Peso",
    phoneCode: "+54",
    ratePerCode: 8.0,
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    currency: "CLP",
    currencySymbol: "CLP$",
    currencyName: "Chilean Peso",
    phoneCode: "+56",
    ratePerCode: 7.5,
  },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    currency: "COP",
    currencySymbol: "COL$",
    currencyName: "Colombian Peso",
    phoneCode: "+57",
    ratePerCode: 32.0,
  },
  {
    code: "PE",
    name: "Peru",
    flag: "🇵🇪",
    currency: "PEN",
    currencySymbol: "S/",
    currencyName: "Peruvian Sol",
    phoneCode: "+51",
    ratePerCode: 0.03,
  },

  // Additional African & Global Markets
  {
    code: "AO",
    name: "Angola",
    flag: "🇦🇴",
    currency: "AOA",
    currencySymbol: "Kz",
    currencyName: "Angolan Kwanza",
    phoneCode: "+244",
    ratePerCode: 7.0,
  },
  {
    code: "BW",
    name: "Botswana",
    flag: "🇧🇼",
    currency: "BWP",
    currencySymbol: "P",
    currencyName: "Botswana Pula",
    phoneCode: "+267",
    ratePerCode: 0.11,
  },
  {
    code: "CD",
    name: "DR Congo",
    flag: "🇨🇩",
    currency: "CDF",
    currencySymbol: "FC",
    currencyName: "Congolese Franc",
    phoneCode: "+243",
    ratePerCode: 22.0,
  },
  {
    code: "DZ",
    name: "Algeria",
    flag: "🇩🇿",
    currency: "DZD",
    currencySymbol: "DA",
    currencyName: "Algerian Dinar",
    phoneCode: "+213",
    ratePerCode: 1.08,
  },
  {
    code: "TN",
    name: "Tunisia",
    flag: "🇹🇳",
    currency: "TND",
    currencySymbol: "DT",
    currencyName: "Tunisian Dinar",
    phoneCode: "+216",
    ratePerCode: 0.025,
  },
  {
    code: "ZM",
    name: "Zambia",
    flag: "🇿🇲",
    currency: "ZMW",
    currencySymbol: "ZK",
    currencyName: "Zambian Kwacha",
    phoneCode: "+260",
    ratePerCode: 0.22,
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    flag: "🇿🇼",
    currency: "USD",
    currencySymbol: "$",
    currencyName: "US Dollar",
    phoneCode: "+263",
    ratePerCode: 0.008,
  },
  {
    code: "MU",
    name: "Mauritius",
    flag: "🇲🇺",
    currency: "MUR",
    currencySymbol: "₨",
    currencyName: "Mauritian Rupee",
    phoneCode: "+230",
    ratePerCode: 0.36,
  },
  {
    code: "NA",
    name: "Namibia",
    flag: "🇳🇦",
    currency: "NAD",
    currencySymbol: "N$",
    currencyName: "Namibian Dollar",
    phoneCode: "+264",
    ratePerCode: 0.15,
  },
  {
    code: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    currency: "TRY",
    currencySymbol: "₺",
    currencyName: "Turkish Lira",
    phoneCode: "+90",
    ratePerCode: 0.27,
  },
  {
    code: "IL",
    name: "Israel",
    flag: "🇮🇱",
    currency: "ILS",
    currencySymbol: "₪",
    currencyName: "Israeli Shekel",
    phoneCode: "+972",
    ratePerCode: 0.03,
  },
  {
    code: "HK",
    name: "Hong Kong",
    flag: "🇭🇰",
    currency: "HKD",
    currencySymbol: "HK$",
    currencyName: "Hong Kong Dollar",
    phoneCode: "+852",
    ratePerCode: 0.062,
  },
  {
    code: "TW",
    name: "Taiwan",
    flag: "🇹🇼",
    currency: "TWD",
    currencySymbol: "NT$",
    currencyName: "New Taiwan Dollar",
    phoneCode: "+886",
    ratePerCode: 0.26,
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    currency: "PLN",
    currencySymbol: "zł",
    currencyName: "Polish Złoty",
    phoneCode: "+48",
    ratePerCode: 0.032,
  },
  {
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+30",
    ratePerCode: 0.007,
  },
  {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    currency: "EUR",
    currencySymbol: "€",
    currencyName: "Euro",
    phoneCode: "+358",
    ratePerCode: 0.007,
  },
];

// Sort alphabetically by name with Nigeria and major hubs easily selectable
export const SORTED_COUNTRIES = [...COUNTRIES].sort((a, b) => a.name.localeCompare(b.name));

export function getCountryByCode(code: string): CountryInfo {
  const match = COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return (
    match || {
      code: code.toUpperCase(),
      name: code.toUpperCase(),
      flag: "🌐",
      currency: "USD",
      currencySymbol: "$",
      currencyName: "US Dollar",
      phoneCode: "+1",
      ratePerCode: 0.008,
    }
  );
}

export function formatCountryCurrency(amount: number, countryCode: string): string {
  const info = getCountryByCode(countryCode);
  return `${info.currencySymbol}${amount.toLocaleString(undefined, {
    minimumFractionDigits: info.ratePerCode < 1 ? 2 : 0,
    maximumFractionDigits: 2,
  })}`;
}
